---
- name: Update Cache #apt update
  apt:
    update_cache: yes

- name: Install nginx #apt install nginx
  apt:
    name: nginx

- name: copy index.html
  copy:
    src: site.html
    dest: /var/www/html